<?php

namespace Winify\DompdfLoadr\Composer;

use Composer\Util\Filesystem;

/**
 * Class ConstantInitiator
 */
class ConstantInitiator {

	/**
	 * @param \Composer\Script\Event $event
	 * @return bool
	 * @throws \Exception
	 */
	static public function generate(\Composer\Script\Event $event) {
		$event->getIO()->write('<info>Initiate dompdf constants</info>');

		$composer = $event->getComposer();
		$config = $composer->getConfig();

		$filesystem = new Filesystem();
		$filesystem->ensureDirectoryExists($config->get('vendor-dir'));
		$vendorPath = $filesystem->normalizePath(realpath($config->get('vendor-dir')));

		$originalAutoloadFileContent = str_replace('<?php', '', file_get_contents($vendorPath . '/autoload.php'));
		$autoloadFileContent = <<<EOF
<?php


// autoload.php @generated by Winify/DompdfLoadr

define("DOMPDF_ENABLE_AUTOLOAD", FALSE);
define("DOMPDF_ENABLE_FONTSUBSETTING", TRUE);
define("DOMPDF_ENABLE_CSS_FLOAT", TRUE);

require_once __DIR__ . '/dompdf/dompdf/dompdf_config.inc.php';

$originalAutoloadFileContent
EOF;
		file_put_contents($vendorPath . '/autoload.php', $autoloadFileContent);

		$originalDompdfFontCacheFileContent = str_replace(') ?>', '', file_get_contents($vendorPath . '/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php'));

		$dompdfFontCacheFileContent = <<<EOF
$originalDompdfFontCacheFileContent
	'times' => array(
		'normal' => '$vendorPath/winify/dompdf-loadr/fonts/times',
		'bold' => '$vendorPath/winify/dompdf-loadr/fonts/timesbd',
		'italic' => $vendorPath/winify/dompdf-loadr/fonts/timesi',
		'bold_italic' => $vendorPath/winify/dompdf-loadr/fonts/timesbi'
	),
	'arial' => array(
		'normal' => $vendorPath/winify/dompdf-loadr/fonts/arial',
		'bold' => $vendorPath/winify/dompdf-loadr/fonts/arialbd',
		'italic' => $vendorPath/winify/dompdf-loadr/fonts/ariali',
		'bold_italic' => $vendorPath/winify/dompdf-loadr/fonts/arialbi'
	),
) ?>
EOF;
		file_put_contents($vendorPath . '/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php', $dompdfFontCacheFileContent);

		return true;
	}

}
